./test.sh "-b text1.txt"
./test.sh "-v text1.txt"
./test.sh "-n text1.txt"
./test.sh "-s text1.txt"
./test.sh "-t text1.txt"
./test.sh "-e text1.txt"

./test.sh "-b -e text1.txt"
./test.sh "-b -n text1.txt"
./test.sh "-s -n text1.txt"
./test.sh "-e -n text1.txt"
./test.sh "-s -n text1.txt"

./test.sh "-e -n -s text2.txt"
./test.sh "-b -e -s text2.txt"
./test.sh "-b -n -s text2.txt"
./test.sh "-s -n -v text2.txt"
./test.sh "-e -n -s text2.txt"
./test.sh "-s -n -e text2.txt"

./test.sh "-e -n -s text1.txt text2.txt"
./test.sh "-b -n -s text1.txt text2.txt"
./test.sh "-s -n -v text1.txt text2.txt"
./test.sh "-e -n -s text1.txt text2.txt"
./test.sh "-s -n -e text1.txt text2.txt"